### ISSUE TITLE
GEN_VER_DIGITAL_VERSION 

### ISSUE THREAD

**Issue by MattiasEppler** [Thell/git-vs-versioninfo-gen#3]
If I build a version without a git tag the GEN_VER_DIGITAL_VERSION  looks like 4,0,1,g0bfa026.
This is not correct with the documentation:

GEN_VER_DIGITAL_VERSION
16 bit int values representing Major, Minor, Fix, Patches.

g0bfa026 is not an int value. And GEN_VER_DIGITAL_VERSION can not be used for FileVersion which only allows int values.

**Comment by MattiasEppler** [comment]
Is this fixed or why is this closed without any comment?

**Comment by Thell** [comment]
It was closed without comment because it has been inactive for a year and I didn't think anyone would care. As for a fix...

> If I build a version without a git tag

As it says in the overview:
> project uses an MS-DOS batch file to parse the output of git-describe

and as git describe states

> the most recent tag that is reachable from a commit

The fix is, don't do builds without a tag.
